spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eatgo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: eatgo
    password: eatgo

  jpa:
    hibernate:
      ddl-auto: update

#---
#
#spring:
#  profiles: test
#  data:source:
#
##db source
#spring.datasource.url=jdbc:mysql://localhost:3306/eatgo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#
##db response name
#spring.datasource.username=eatgo
#
##db response password
#spring.datasource.password=eatgo
#
##spring.jpa.properties.hibernate.id.new_generator_mappings=false